name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qt:
          - 5.9.1
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1  # not v2!
      with:
        path: ../Qt
        key: ${{ runner.os }}-${{ matrix.qt }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ matrix.qt }}
        modules: 'qtwidgets qtwebenginewidgets qtnetwork qtxml qtprintsupport qtsql qtmultimedia'
    # - run: sudo apt-get install qtbase5-dev qtbase5-dev-tools qttools5-dev-tools libqt5webkit5-dev qtmultimedia5-dev
    - name: make
      run: |
        mkdir _build && cd _build
        qmake CONFIG+=release PREFIX=/usr ../QuiteRSS.pro
        make
        make install
